### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by reaper666735** [Sonaza/DressUp#11]
Hello,

while using the Armory addon to link a spell from the Spellbook, i get this error from Dressup lol :

4x DressUp\comms.lua:189: attempt to index local 'link' (a number value)
DressUp\comms.lua:189: in function `HandleModifiedItemClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
link = 79134
(*temporary) = nil
(*temporary) = 79134
(*temporary) = nil
(*temporary) = "attempt to index local 'link' (a number value)"
OriginalHandleModifiedItemClick = <function> defined @FrameXML\ItemButtonTemplate.lua:135

could just be a taint from Armory itself but i prefer to warn both addon authors :p

**Comment by Sonaza** [comment]
Probably a bug in this addon and even if it's not I can at least add extra checks to make sure it doesn't happen again.

It's used to handle custom chat links and your Armory addon may also be using such ones except my addon always expects to have a string value which Armory doesn't seem to give.

Fixed in version 3.0.3.
